extends: relaxed

rules:
    comments: enable
    comments-indentation: disable

    line-length:
        max: 170
        level: error

    indentation:
        level: error
        indent-sequences: consistent
