receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: $SUMO_OTLP_HTTP_ENDPOINT_URL

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
  telemetry:
    logs:
      level: info
    metrics:
      level: none
