receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: ${env:SUMO_OTLP_HTTP_ENDPOINT_URL}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
  telemetry:
    logs:
      level: debug
    metrics:
      level: none
