name: Pull Request Build - Python

on:
  pull_request:
    paths:
      - 'python/**'
      - 'opentelemetry-lambda/**'
      - '.github/workflows/*-python.yml'
      - '.github/workflows/tests.yml'
      - '!python/sample-apps/template.yaml'
      - '!**/*.md'

jobs:
  build-artifacts:
    uses: ./.github/workflows/build-artifacts.yml
    with:
      BUILD_COMMAND: make build-python
      LANGUAGE: python
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-python
      ARTIFACT_NAME: ${{ github.head_ref }}

  create-dev-lambda-layer:
    needs: build-artifacts
    uses: ./.github/workflows/publish-dev-layer.yml
    with:
      ARTIFACT_ARCHIVE_BASE_NAME: opentelemetry-python
      ARTIFACT_NAME: ${{ github.head_ref }}
      LANGUAGE: python

  run-tests:
    needs: create-dev-lambda-layer
    uses: ./.github/workflows/tests.yml
    with:
      LANGUAGE: python
      LAYER_ARN_AMD64: ${{ needs.create-dev-lambda-layer.outputs.lambdalayeramd64 }}
      LAYER_ARN_ARM64: ${{ needs.create-dev-lambda-layer.outputs.lambdalayerarm64 }}
